[tool.poetry]
name = "pybay23project"
version = "0.1.0"
description = ""
authors = ["Salar Rahmanian <code@softinio.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
attrs = "^23.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
